---
environments:
  dev:
    docker:
      APP: frontendtest
      VERSION: "0.1"
      registry: ecr
      url: .dkr.ecr.us-east-1.amazonaws.com
      platforms: linux/amd64
      filename: Dockerfile  
      filepath: .
      arguments:
        ENVIRONMENT: dev
    
    microservice:
      cluster: dev-ecs_cluster
      cpu: 256
      memory: 256
      replicas: 1
      domain_name: frontendtest.dev.x.com
      variables:
        DATABASE: louvre
        USERNAME: admin
      secrets:
        PASSWORD: dev/db/frontendtest/password
        ENDPOINT: dev/db/frontendtest/endpoint
